# Generated by Django 4.2.2 on 2023-10-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='items',
        ),
    ]
