# Generated by Django 4.2.2 on 2023-10-04 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_remove_quotation_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quotation_item', to='quotations.item', verbose_name='Item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='quotations.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'QuotationItem',
                'verbose_name_plural': 'QuotationItems',
                'ordering': ['id'],
            },
        ),
    ]
