# Generated by Django 4.2.2 on 2023-10-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='stakeholders.client', verbose_name='Client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
