# Generated by Django 4.2.2 on 2023-10-04 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('reg_no', models.CharField(max_length=15, verbose_name='Registered Number')),
                ('contact_no', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('address', models.CharField(max_length=1023, verbose_name='Address')),
                ('bank_name', models.CharField(max_length=127, verbose_name='Bank Name')),
                ('branch_name', models.CharField(max_length=127, verbose_name='Branch Name')),
                ('bank_acc_num', models.CharField(max_length=127, verbose_name='Account Number')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salary Amount')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('is_advance', models.BooleanField(default=False, verbose_name='Is Advance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='employees.employee', verbose_name='Attendance')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salaries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Date')),
                ('ot_hours', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='OT Hours')),
                ('leave_type', models.CharField(max_length=127, verbose_name='Leave Type')),
                ('notes', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.employee', verbose_name='Attendance')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['id'],
            },
        ),
    ]
