# Generated by Django 4.2.2 on 2023-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_leave',
            field=models.BooleanField(default=False, verbose_name='Is Leave'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Leave Type'),
        ),
    ]
