# Generated by Django 4.2.2 on 2023-10-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance_is_leave_alter_attendance_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='employees.employee', verbose_name='Employee'),
        ),
    ]
